title: Telemedicine and Health Disparities during COVID 19
email: ltong@uwm.edu
baseurl: ""
url: ""
twitter_username: tongling
youtube: tongling
# Build settings
theme: minima
minima:
  social_links:
    twitter: tongling
    website: tongling.github.io
